a(
  [
    ".",
    "the rest are old... from 2015",
    "Watching the walking dead. In an empty penthouse. Had a great weekend. Thanks everyone!",
    "Just went on the roller coaster",
    "In the penthouse - come on up!",
    "Waking up?",
    "Heading to harrahs - carnival bar, at the",
    "ZUMANITY",
    "In the penthouse ready to happy hour!",
    "Going to the essentials market",
    "Hanging in the penthouse. You can too!",
    "Walking",
    "At the NYNY arcade. Skee ball anyone?",
    "Skipping pool - getting started on the day",
    "The Andrew is still sleeping things off. Come to the penthouse if interested in hanging out. Feel free to head over to the pool; we shall be fashionably late.",
    "Sleeping it off",
    "Assembling in the Ritz PENTHOUSE: rm 3355 to depart for fremont at 10pm",
    "Super mega cocktail hours in the Ritz PENTHOUSE: rm 3355",
    "In the Ritz PENTHOUSE: rm 3355",
    "Changing rooms",
    "Walking aimlessly",
    "On hold",
    "Watching full house",
    "At NYNY; now accepting visitors!",
    "in stealth mode in Vegas",
    "test message from phine",
    "testMessage",
    "in stealth mode in Vegas",
    "Not in Vegas"
  ]
);
